server:
  port: 8201
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.221.130:7010