server:
  port: 8200
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.zaxxer.hikari.HikariDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stl_tuling_2021?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.221.130:7010
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.spnc.entities
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: info
    com.spnc.mapper: debug